---
title: "DS_TA_audition"
author: "Duzhi Zhao"
date: "7/2/2020"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)

knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  fig.width = 8, 
  fig.height = 6,
  out.width = "80%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

# Import and tidy dataset
```{r}
dog_import = readxl::read_excel("./data/dog_weights.xlsx") 

dog_data = readxl::read_excel("./data/dog_weights.xlsx", skip = 2) %>% 
  janitor::clean_names() %>% 
  mutate(date = janitor::excel_numeric_to_date(as.numeric(date)),
         weight_raisin_lbs = as.numeric(substr(raisin, 1, 2)) + as.numeric(substr(raisin, 3, 5))*0.0625,
         weight_simone_lbs = as.numeric(substr(simone, 1, 2)) + as.numeric(substr(simone, 3, 5))*0.0625,
         weight_gagne_lbs = as.numeric(substr(gagne, 1, 2)) + as.numeric(substr(gagne, 3, 5))*0.0625,
         rer_raisin = ((weight_raisin_lbs*0.453592)^0.75)*70,
         rer_simone = ((weight_simone_lbs*0.453592)^0.75)*70,
         rer_gagne = ((weight_gagne_lbs*0.453592)^0.75)*70) %>% 
  # Transfer all units into pounds
  # RER stands for Resting Energy Requirement (18 lb dog = 339 cal), calculated based on the following source:
  # https://vet.osu.edu/vmc/companion/our-services/nutrition-support-service/basic-calorie-calculator
  select(date, 7:12) %>%  # Select columns of interest %>% 
  drop_na(date) # Remove one observation without date information
```

# Plot
```{r}

```

